name: cyberfly_mobile_node
description: "Cyberfly P2P Mobile Node - Flutter app with Rust native library for decentralized networking"
publish_to: 'none'

version: 1.0.2+6

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_rust_bridge: ^2.11.1
  rust_lib_cyberfly_mobile_node:
    path: rust_builder
  freezed_annotation: ^2.4.4
  tuple: ^2.0.2
  meta: ^1.16.0
  path_provider: ^2.1.5
  # Wallet & Kadena
  bip39: ^1.0.6
  slip_0010_ed25519: ^3.2.0
  kadena_dart_sdk: ^2.3.2
  convert: ^3.1.2
  shared_preferences: ^2.3.4
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.2
  http: ^1.2.2
  local_auth: ^2.3.0
  # Background Service
  flutter_background_service: ^5.0.12
  flutter_background_service_android: ^6.2.8
  flutter_local_notifications: ^18.0.1
  # App Info
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.2
  # QR Code Scanner
  mobile_scanner: ^6.0.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  ffigen: ^20.1.1
  freezed: ^2.5.7
  build_runner: ^2.4.0

dependency_overrides:
  pinenacl: ^0.6.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
